export const DELIVERED_STATUS = "DELIVERED";
export const SHIPPING_STATUS = "SHIPPING";
export const WAITING_PICKUP_STATUS = "WAITING FOR PICKUP";
export const WAITING_CONFIRM_STATUS = "WAITING FOR CONFIRM";
export const COMPLETED_STATUS = "COMPLETED";
export const CANCELING_STATUS = "CANCELING";
